
```{r load_library}
library(ggplot2)
library(scales)
```

1.

```{r 1}
plot0 <- qplot(
			   date,
			   psavert,
			   data = economics,
			   geom = "line"
			   )
plot0.1 <- plot0 +
	ylab("Personal savings rate") +
#    geom_hline(xintercept = 0, colour = "grey50") +
	scale_x_date(
				 labels = date_format("%Y"),
				 minor_breaks = date_breaks("1 years"),
				 breaks = seq(as.Date("1967-1-1"), as.Date("2007-2-1"), 5 * 366)
				 )

plot1 <- plot0.1 +
	theme(
		  panel.grid.minor = element_line(color='white'),
		  panel.grid.minor.y = element_line(size=0.5, color='white')
		  ) +
	scale_y_continuous(
					   breaks = c(0, 5, 10)
					   )

plot1

plot2 <- plot1 +
	scale_x_date(
				 labels = date_format("%Y"),
				 minor_breaks = date_breaks("1 years"),
				 breaks = seq(as.Date("1967-1-1"), as.Date("2007-2-1"), 10 * 366)
				 )

plot2

plot3 <- plot2 +
	scale_x_date(
				 limits = as.Date(c("2004-1-1", "2005-1-1")),
				 labels = date_format("%Y-%m-%d"),
				 breaks = as.Date(c("2004-1-1", "2004-4-1", "2004-7-1", "2004-10-1", "2005-1-1"))
				 )

plot3
```

2.

```{r 2}
head(diamonds)
p4  <- ggplot(diamonds, aes(x = cut, fill = color))
p4 + labs(x = NULL, y = NULL) + geom_bar(aes(y = ..count..)) +
	coord_polar()

part_diamonds <- subset(diamonds, clarity == "SI2")
p5 <- ggplot(part_diamonds, aes(x = price, y = carat, color = color, shape = cut))
p5 + labs(x = "price", y = "carat") + geom_point() + coord_polar()
```

